/**
 * Turns the built dashboard into a module the compiled binary carries.
 *
 * `bun build --compile` bundles what it can resolve statically, so the assets arrive as a
 * generated source file rather than as a directory read at startup. The result is what makes
 * `bastion` one file: an install that also has to ship a directory of assets is an install with a
 * second way to go wrong, and a box with no route to the internet cannot fetch the missing half.
 *
 *     bun run --cwd dashboard build
 *     bun warden/scripts/embed-dashboard.ts
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const built = join(root, '..', 'dashboard', '.output', 'public');
const out = join(root, 'src', 'dashboard-assets.ts');

function walk(dir: string, found: string[] = []): string[] {
	for (const entry of readdirSync(dir)) {
		const path = join(dir, entry);
		if (statSync(path).isDirectory()) walk(path, found);
		else found.push(path);
	}
	return found;
}

/**
 * `--restore` writes the empty form back.
 *
 * The real module is a megabyte of base64 and must never be committed, but the source imports it
 * statically, so it cannot simply be absent either. The committed file is the empty one; a build
 * fills it, compiles, and puts it back, which leaves `git status` clean after the normal path.
 */
const restoring = process.argv.includes('--restore');

let files: string[] = [];
if (!restoring) {
	try {
		files = walk(built).sort();
	} catch {
		process.stderr.write(`no build at ${built}; run \`bun run --cwd dashboard build\` first\n`);
		process.exit(2);
	}
}

const entries = files.map((path) => {
	const key = relative(built, path).split('\\').join('/');
	return `\t'${key}': '${readFileSync(path).toString('base64')}'`;
});

const source = [
	'// generated by warden/scripts/embed-dashboard.ts; do not edit',
	'',
	'/** the built dashboard, base64 per file, decoded once on first use */',
	entries.length === 0
		? 'export const DASHBOARD_FILES: Record<string, string> = {};'
		: [
				'export const DASHBOARD_FILES: Record<string, string> = {',
				entries.join(',\n'),
				'};'
			].join('\n'),
	''
].join('\n');

writeFileSync(out, source);
if (restoring) {
	process.stdout.write(`restored ${relative(root, out)} to its empty form\n`);
} else {
	const bytes = files.reduce((total, path) => total + statSync(path).size, 0);
	process.stdout.write(
		`embedded ${files.length} files, ${bytes} bytes, into ${relative(root, out)}\n`
	);
}
