/**
 * Turns the built dashboard into a module the compiled binary carries.
 *
 * `bun build --compile` bundles what it can resolve statically, so the assets arrive as a
 * generated source file rather than as a directory read at startup. The result is what makes
 * `bastion` one file: an install that also has to ship a directory of assets is an install with a
 * second way to go wrong, and a box with no route to the internet cannot fetch the missing half.
 *
 *     bun run --cwd dashboard build
 *     bun warden/scripts/embed-dashboard.ts
 */

import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const built = join(root, '..', 'dashboard', '.output', 'public');
const out = join(root, 'src', 'dashboard-assets.ts');

function walk(dir: string, found: string[] = []): string[] {
	for (const entry of readdirSync(dir)) {
		const path = join(dir, entry);
		if (statSync(path).isDirectory()) walk(path, found);
		else found.push(path);
	}
	return found;
}

// `--if-missing` is the install hook: the generated module is not committed, because it is a
// compiled output, but the source imports it statically, so a fresh clone needs the empty form to
// exist before anything typechecks
const ifMissing = process.argv.includes('--if-missing');
if (ifMissing && existsSync(out)) process.exit(0);

let files: string[] = [];
try {
	files = walk(built).sort();
} catch {
	if (!ifMissing) {
		process.stderr.write(`no build at ${built}; run \`bun run --cwd dashboard build\` first\n`);
		process.exit(2);
	}
}

const entries = files.map((path) => {
	const key = relative(built, path).split('\\').join('/');
	return `\t'${key}': '${readFileSync(path).toString('base64')}'`;
});

const source = [
	'// generated by warden/scripts/embed-dashboard.ts; do not edit',
	'',
	'/** the built dashboard, base64 per file, decoded once on first use */',
	'export const DASHBOARD_FILES: Record<string, string> = {',
	entries.join(',\n'),
	'};',
	''
].join('\n');

writeFileSync(out, source);
const bytes = files.reduce((total, path) => total + statSync(path).size, 0);
process.stdout.write(
	`embedded ${files.length} files, ${bytes} bytes, into ${relative(root, out)}\n`
);
